### ISSUE TITLE
failure to integrate with budgetkey-app-search

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/budgetkey-ng2-components#5]
it seems that after the changes in #2 it is not possible to integrate with budgetkey-app-search

the directory structure seems to have changed, which requires changes in the app as well

**Comment by OriHoch** [comment]
@akariv @kravets-levko

**Comment by kravets-levko** [comment]
The only breakable change is extracting embedded css into external file - now it should be manually added to each application. There are several reasons why I did so, the main one is that Angular will load stylesheets specified in `styles`/`styleUrls` via XHR, and therefore it's impossible to minify, optimize, merge and it's hard to cache and reuse stylesheets.

**Comment by kravets-levko** [comment]
@OriHoch To fix UI issues, now applications should do some [extra job](https://github.com/OpenBudget/budgetkey-app-sample/pull/8). But there is also another issue - when linking library via `npm link / npm install <folder>`, `webpack` fails to build app; removing `node_modules` and `package-lock.json` in library's folder helps, but then it's impossible to run `npm prepublish`. 100% works copying files from `budgetkey-ng2-components` (`lib`, `src`, `assets`) to `<app>/node_modules/budgetkey-ng2-components`, but it seems to be not so great solution as well...

**Comment by kravets-levko** [comment]
@OriHoch Seems that I found a perfect solution: [`npm pack`](https://docs.npmjs.com/cli/pack) + [`npm install <tarball file>`](https://docs.npmjs.com/cli/install) - it does exactly what we need (including running all lifecycle scripts and installing only necessary dependencies). I'll create a script tomorrow, and then we'll try it :wink:

**Comment by OriHoch** [comment]
I tried that.. and some other ways too.. didn't work :disappointed:

**Comment by kravets-levko** [comment]
@OriHoch Can you try [this](https://github.com/OpenBudget/budgetkey-ng2-components/pull/6)?

**Comment by OriHoch** [comment]
looks like it works! thanks

**Comment by kravets-levko** [comment]
I'll ask somebody to merge it
