### ISSUE TITLE
hide footer flag not working

### ISSUE THREAD

**Issue by YontiLevin** [OpenBudget/budgetkey-ng2-components#8]

**Comment by OriHoch** [comment]
I'm not familiar with hide footer flag, but showFooter=false seems to work in the example app - 

https://github.com/OpenBudget/budgetkey-ng2-components/commit/dc14355599e78ecfb400f48c75d1c45663754155

**Comment by YontiLevin** [comment]
don't really remember why i raised that issue. 
it was long ago.
if it is working now then the issue can be closed
